name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Performing Type Check
        run: bun run type-check

      - name: Performing Lint
        run: bun run lint

      - name: Performing Format
        run: bun run format

      - name: Performing Build
        run: bun run build
